apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v6kl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v6kl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v6kl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v6kl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v6kl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jhiu-tenant/rhtap-demo-app/hacbs-test-project-v6kl@sha256:a732ece5a368074287f4e1c34bf454743ce6f0bcaffec2d921998acdabf689fa
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
